name: Deploy to Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Use the Node.js version your project requires

    - name: Install dependencies
      run: npm install

    - name: Build the application
      run: npm run build

    - name: Install Vercel CLI
      run: npm install -g vercel

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} # Use your Vercel token stored in GitHub Secrets
      run: vercel --prod --token $VERCEL_TOKEN
